### ISSUE TITLE
Bugs & some inconsistencies

### ISSUE THREAD

**Issue by thebiggestmac** [abhinavmishra14/alfresco62ga-solr-dist-setup#2]
Installation_instructions.txt, line #138

  $ sudo chmod -R 755 /usr/local/alfresco-search-services/*

should be

  $ sudo chmod -R 755 /usr/local/alfresco-search-services/

since we have nothing inside yet, and it'll get an error, or what?

Many times .bash_profile is edited, but WHOSE ONE? Is it the same or not? Better use absolute paths.

**Comment by abhinavmishra14** [comment]
Thanks @thebiggestmac for reviewing the instructions.

1- For line #138, you could use either of the commands. It won’t give any errors. I have removed the unused commands

2- .bash_profile is edited 3 times during the course of setup steps. This is for the user you logged in onto centos. In this case user is ‘centos’. Example - It maps to : /home/centos/.bash_profile
   
> To add java path
> To add alfresco content services path
> To add alfresco search services path

**Comment by abhinavmishra14** [comment]
Closing the issue as the clarification has been provided and necessary changes has been made as well. Thanks for raising the issue and helping
